run:
  # default: '1m'
  timeout: '5m'

  # default: []
  build-tags:
    - 'all'

  # default: ''
  modules-download-mode: 'readonly'

  # default: false
  allow-parallel-runners: true

linters:
  enable:
    - 'asciicheck'
    - 'bodyclose'
    - 'depguard'
    - 'dogsled'
    - 'errcheck'
    - 'errorlint'
    - 'copyloopvar'
    - 'gofmt'
    - 'gofumpt'
    - 'goheader'
    - 'goimports'
    - 'gomodguard'
    - 'goprintffuncname'
    - 'gosec'
    - 'govet'
    - 'ineffassign'
    - 'makezero'
    - 'misspell'
    - 'noctx'
    - 'prealloc'
    - 'predeclared'
    - 'revive'
    - 'sqlclosecheck'
    - 'staticcheck'
    - 'typecheck'
    - 'unconvert'
    - 'whitespace'
  disable:
    - 'unused'
    - 'paralleltest'
    - 'stylecheck'
    - 'gosimple'
issues:
  # default: []
  exclude:
    - '^S1023:' # staticcheck: redundant returns help with http handlers
    - '^SA3000:' # staticcheck: not required in Go 11.4+
    - '^G505:' # gosec: we use crypto/sha1 for some HMACs
    - '^Range statement' # paralleltest: false positives
    - '^var-declaration:' # revive: false positive
    - '^exported:' # revive: backwards-compat

  # default: []
  exclude-dirs:
    - 'node_modules'

  # default: true
  exclude-dirs-use-default: false

  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  depguard:
    rules:
      main:
        list-mode: lax # allow unless explicitly denied
        allow:
          - $all
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
