DROP MATERIALIZED VIEW IF EXISTS m_v_towns CASCADE;

DROP INDEX IF EXISTS idx_m_v_towns_city_id CASCADE;

DELETE FROM city_towns CASCADE;
DELETE FROM cities CASCADE;

DROP TABLE IF EXISTS city_towns CASCADE;
DROP TABLE IF EXISTS cities CASCADE;

DROP TABLE IF EXISTS files;

DROP TYPE IF EXISTS file_generate_reasons;